spring:
  application:
    name: spring-cloud-ribbon
 
server:
  port: 8888
 
ping-server:
  ribbon:
    eureka:
      enabled: false
    #listOfServers: localhost:8079,localhost:8075,localhost:8074
    listOfServers: localhost:8079,localhost:8075
    ServerListRefreshInterval: 15000 